CREATE DATABASE TravelPortal;

USE TravelPortal;

CREATE TABLE USER (
    ID INT NOT NULL auto_increment,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    USER_ROLE INT(4) NOT NULL,
    PRIMARY KEY (ID)
);

-- CREATE TABLE ROLE (
--     ROLE_ID INT NOT NULL auto_increment,
--     ROLE_NAME VARCHAR(50) NOT NULL,
--     PRIMARY KEY (ROLE_ID)
-- );
--
-- CREATE TABLE PRIVILEGE (
--     PRIVILEGE_ID INT NOT NULL auto_increment,
--     SERVICE INT NOT NULL auto_increment,
--     METHOD VARCHAR(50) NOT NULL,
--     PRIMARY KEY (PRIVILEGE_ID)
-- );

CREATE TABLE USER_TOKEN (
    ID INT NOT NULL auto_increment,
    EMAIL VARCHAR(20) NOT NULL,
    TOKEN VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE AIRLINE_OFFER (
    OFFER_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ORIGIN VARCHAR(50) NOT NULL ,
    DESTINATION VARCHAR(50) NOT NULL,
    PRICE INT(10) NOT NULL,
    CURRENCY VARCHAR(5) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    AVAILABLE_INV INT(10) NOT NULL
);
